root: true

env:
  node: true
  es6: true

ignorePatterns:
  - dist/
  - node_modules/
  - typings/

extends:
  - eslint:recommended
  - prettier

plugins:
  - prettier

rules:
  comma-dangle:
    - off

  complexity:
    - warn
    - max: 25

  curly:
    - error
    - multi

  id-length:
    - error
    - min: 2
      exceptions:
        - a
        - b
        - h
        - i
        - j
        - k

  indent:
    - off

  max-statements:
    - warn
    - 25

  no-param-reassign:
    - error
    - props: false

  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true

  no-warning-comments:
    - warn

  object-curly-spacing:
    - off

  prefer-destructuring:
    - error
    - object: true
      array: false

  quotes:
    - off

  radix:
    - error
    - as-needed

overrides:
  - files:
      - rollup.config.js

    parserOptions:
      sourceType: module

  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - prettier/@typescript-eslint

    plugins:
      - "@typescript-eslint"

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - "./tsconfig.json"
        - "./tsconfig.test.json"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

      "@typescript-eslint/no-unsafe-member-access":
        - warn

  - files:
      - "**/__tests__/**/*.spec.{j,t}s?(x)"

    env:
      jest: true

    rules:
      id-length: off
      max-lines-per-function: off
      "@typescript-eslint/no-explicit-any": off
      "@typescript-eslint/no-unsafe-member-access": off
